### ISSUE TITLE
Registration password

### ISSUE THREAD

**Issue by jbrucker** [EveGroup/EveHolder#107]
On the registration screen, if the user's password does not meet some complexity requirements
then the password is rejected, but there is no feedback on the screen.
It just redisplays the registration page.

**Comment by KongtappV** [comment]
the issue has been fixed thank you for informing me.
now the text's color is white so the error text would be visible.
![image](https://user-images.githubusercontent.com/59852173/102748480-d607fa80-4394-11eb-8df0-0af757e7438a.png)
