### ISSUE TITLE
An conflict at installation

### ISSUE THREAD

**Issue by lisbono2001** [EveGroup/EveHolder#84]
### When I tried to install at creating virtual-env step, pipenv can't find the right path to my current Python version (3.8) and the LANG in my profile wasn't set.  
This may occurred because I'm currently using Python 3.8 and pipenv requires Python 3.7 and also my LANG in ~/.profile and ~/.bash_profile have some issue. I hope this would help someone that have issue like me.   
```
Warning: the environment variable LANG is not set!
We recommend setting this in ~/.profile (or equivalent) for proper expected behavior.
Creating a virtualenv for this project…
Pipfile: /Users/theetouchkasemarnontana/Desktop/EveHolder/Pipfile
Using /Library/Frameworks/Python.framework/Versions/3.8/bin/python3 (3.8.0) to create virtualenv…
Warning: Your Pipfile requires python_version 3.7, but you are using 3.8.0 (/Users/t/.local/share/v/E/bin/python).
  $ pipenv --rm and rebuilding the virtual environment may resolve the issue.
  $ pipenv check will surely fail.
Pipfile.lock (5d1173) out of date, updating to (3d7b8b)…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Building requirements...
Resolving dependencies...
✘ Locking Failed! 
```
###
For those who use zsh shell, you must add those lines to your ~/.zshrc
```
export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
```
Then I reload the bash profile with: source ~/.zshrc
[reference](https://stackoverflow.com/questions/49436922/getting-error-while-trying-to-run-this-command-pipenv-install-requests-in-ma)

#### then I set the path to this :
```
$ which python
[path to my Python]
$ pipenv install --python=[path to my Python]
```
[more detail](https://github.com/pypa/pipenv/issues/3996)

After that, I followed Issue #83 and the application work correctly.

**Comment by james31366** [comment]
Thx for report the issues. I'll add this information to our project.

**Comment by pattarinn** [comment]
Thanks for the information :DDD
