### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by patiphan2000** [EveGroup/EveHolder#85]
cloned and install `pipenv` is working fined.

but I found some issue when try to install requirement with
```
pipenv install -r requirements.txt
```

terminal show **Locking Falied!**, same as Issue #84 

**Screenshot of my terminal when executed the command**
<img width="1103" alt="Screen Shot 2020-11-29 at 8 11 14 PM" src="https://user-images.githubusercontent.com/59829863/100543834-fc9ab000-3284-11eb-8278-9baddf6ed6cd.png">

**Comment by james31366** [comment]
U fix the issues?

**Comment by pattarinn** [comment]
We will fix that as soon as possible, thank you!
