### ISSUE TITLE
Installation problem2

### ISSUE THREAD

**Issue by toey10112** [EveGroup/EveHolder#88]
When I type command python manage.py makemigrations, it can't make migrations, and its show this
![image](https://user-images.githubusercontent.com/58396402/100547207-0c6fbf80-3298-11eb-9031-438f243e4e1b.png)
![image](https://user-images.githubusercontent.com/58396402/100547215-1bef0880-3298-11eb-915a-8378f373f105.png)
![image](https://user-images.githubusercontent.com/58396402/100547228-29a48e00-3298-11eb-9ec6-3f3e5ccb4dbe.png)

**Comment by james31366** [comment]
I think your `DATABASE_URL` is wrong. You can delete the `DATABASE_URL` in `.env` file

**Comment by toey10112** [comment]
ok I can run now.
