### ISSUE TITLE
Functionality: User update can accept weird input

### ISSUE THREAD

**Issue by ZEZAY** [EveGroup/EveHolder#94]
I try to update user info with some weird input and found that it accepts:
1. zero and negative phone number
2. blank string as first name and last name

URL: https://eve-holder.herokuapp.com/events/update_information/

![image](https://user-images.githubusercontent.com/44806732/101126692-96b87a80-362e-11eb-90b7-1c1de22a918c.png)

**Comment by metaras** [comment]
thank you
