### ISSUE TITLE
Server error(500) after input javascript in event form.

### ISSUE THREAD

**Issue by Sahadporn** [EveGroup/EveHolder#95]
url:https://eve-holder.herokuapp.com/create_event/

1. In the event form, input javascript
![eve1](https://user-images.githubusercontent.com/59825486/101136651-38949300-3640-11eb-948c-7d19956b5dad.png)

2. Click create event. It's will cause server error(500)
![eve2](https://user-images.githubusercontent.com/59825486/101136730-582bbb80-3640-11eb-8859-641c43cebf7e.png)

**Comment by pattarinn** [comment]
Bug is fixed. Thanks for the reminding.
