### ISSUE TITLE
server error after re search again

### ISSUE THREAD

**Issue by Noboomta** [EveGroup/EveHolder#96]
After I tried to search after I did search, The server error.
![image](https://user-images.githubusercontent.com/53256241/101181750-d5c2ec00-367f-11eb-8489-263db0a8b410.png)
![image](https://user-images.githubusercontent.com/53256241/101181766-da87a000-367f-11eb-8d50-6424353c2f4b.png)
I still can't edit it in my project either. So I think this problem is probably not a big deal.

**Comment by pattarinn** [comment]
Already fix that. Thank you.
