### ISSUE TITLE
Some system message show up

### ISSUE THREAD

**Issue by NarawishS** [EveGroup/EveHolder#97]
I got some unwanted message
![image](https://user-images.githubusercontent.com/59836187/101243034-05c9c800-3730-11eb-97bb-4f63d0c479d4.png)

what i did to get this was
1. I create wrong type of account
2. I deleted that account
3. I create new account
4. I create event using new accout then i see that message show up
it wasn't suppose to be there was it?

**Comment by NarawishS** [comment]
by the way the unwanted message 
Account Deleted (jackyssrw1)

**Comment by metaras** [comment]
Thanks for issue
