### ISSUE TITLE
Creating event error: same end date and pub date

### ISSUE THREAD

**Issue by NarawishS** [EveGroup/EveHolder#98]
I try to create event with same pubdate and enddate then i got this for the first summit
![image](https://user-images.githubusercontent.com/59836187/101243192-10d12800-3731-11eb-9ab3-b7b3fd133392.png)
and then i summit again with same input and i got sever 500
![image](https://user-images.githubusercontent.com/59836187/101243199-1b8bbd00-3731-11eb-9b01-477adff078d0.png)
is this your intention for not being able to host one day event or not?

**Comment by KongtappV** [comment]
the bug is fixed thank you for informing us
